//folder
export const CREATE_FOLDER = "CREATE_FOLDER";
export const UPDATE_FOLDER_NAME = "UPDATE_FOLDER_NAME";
export const UPDATE_FOLDER_COLOUR = "UPDATE_FOLDER_COLOUR";
export const CLOSE_CURRENT_FOLDER = "CLOSE_CURRENT_FOLDER";

//fetch_notes
export const SERVER_FETCH_NOTES = "SERVER_FETCH_NOTES";
export const SERVER_FETCH_NOTES_SUCCESS = "SERVER_FETCH_NOTES_SUCCESS";
export const SERVER_FETCH_NOTES_FAILURE = "SERVER_FETCH_NOTES_FAILURE";
export const LOCAL_FETCH_NOTES = "LOCAL_FETCH_NOTES";

// edit notes
export const CREATE_NOTE = "CREATE_NOTE";
export const REMOVE_NOTE = "REMOVE_NOTE";
export const CHANGE_NOTE_COLOUR = "CHANGE_NOTE_COLOUR";
export const UPDATE_NOTE_SIZE = "UPDATE_NOTE_SIZE";
export const UPDATE_NOTE_TEXT = "UPDATE_NOTE_TEXT";
export const UPDATE_NOTE_LOCATION = "UPDATE_NOTE_LOCATION";
export const UPDATE_NOTE_POSITION = "UPDATE_NOTE_POSITION";
